## Metricbeat configuration
## https://github.com/elastic/beats/blob/master/deploy/docker/metricbeat.docker.yml

metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

metricbeat.modules:
- module: docker
  metricsets:
    - container
    - cpu
    - diskio
    - healthcheck
    - info
    #- image
    - memory
    - network
  hosts: ['unix:///var/run/docker.sock']
  processes: ['.*']
  process.include_top_n:
    by_cpu: 5
    by_memory: 5
  period: 10s
  cpu.metrics:  ["percentages"]
  core.metrics: ["percentages"]
  enabled: true

# - module: system
#   period: 1m
#   metricsets:
#     - filesystem
#     - fsstat
#   processors:
#   - drop_event.when.regexp:
#       system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib)($|/)'

# - module: system
#   period: 15m
#   metricsets:
#     - uptime

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - decode_json_fields:
      fields: ["message"]

setup.ilm.enabled: false
setup.template.enabled: false

output.elasticsearch:
  hosts: ["log-analytics:9200"]
  protocol: "http"
  index: "metricbeat-es-%{+yyyy.MM.dd}"

http.enabled: true
http.host: 0.0.0.0
