filebeat.inputs:
- type: log
  enabled: true
  paths:
    - ./elasticsearch/logs/_elastic*.log

json.keys_under_root: true
json.add_error_key: true
json.message_key: log

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      templates:
        - condition:
            equals.docker.container.image: log-generator
          config:
            - type: container
              # paths:
              #   - /var/lib/docker/containers/**/*.log

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - decode_json_fields:
      fields: ["message"]

setup.ilm.enabled: false
setup.template.enabled: false

# output.elasticsearch:
#   hosts: ["log-analytics:9200"]
#   protocol: "http"
#   index: "filebeat-es-%{+yyyy.MM.dd}"

output.kafka: 
  hosts: ["kafka:9092"] 
  topic: 'log' 
  partition.round_robin: 
    reachable_only: false 
  required_acks: 1 
  compression: gzip 
  max_message_bytes: 1000000