FROM ubuntu:focal

RUN apt-get update -q
RUN DEBIAN_FRONTEND=noninteractive apt-get install \
  -qy wget vim net-tools python3 python3-pip default-jre-headless

RUN pip install pyspark

COPY sparkprog.py /usr/local/src/sparkprog.py
WORKDIR /usr/local/src

ENTRYPOINT ["spark-submit", "--packages", "org.apache.spark:spark-sql-kafka-0-10_2.12:3.3.0,org.elasticsearch:elasticsearch-hadoop:7.14.1", "sparkprog.py"]
